---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: samba
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgCu/+MZA1bDndwNNe5jTIfXQxzP5gau3+l6yHZYygXKJwgmf8V06czHWHN2vkhSlbLa7zIETXtCRtwZqQK7ftWMhzr66gIYNYktsYd9QPgsm1CG46PIQ0VkmIJ45QZhuZ5Dj7WcK1JaBQNxD7VsPCMRyHpYLU7fqCd/zjG1jDVz61VgZhFQNCwglPFi5Jzi80ooTqd/jTP06S354o6mxAI2/Oic4VZC9Cbu0qzxp/NxeJ/s/cj+WFt2cAKkP2O1mp5K1msKuHvzoNERz442YHyJMiMnFxtmN2aKysQImRMV4ALyI6ayKwQbAcEVwROW9G7z6+AZqK3SAf9YEKK8rSu3+VZGFvnEQMKoGoEbiXm+gOZuZ6uobAUdsxpicas4v2MhpsTQ4NVqnT8zODyjL2fwMPdK+kM2TtJbsHhVH2XWuYahidX0226ABjtGcxCrwRQUoB8rKvuZzhqEcVlPB67qwYKM5bLYLE5KqHgZayhW4TTnauZPv1Ux1UPKPvVK54pb/i0cC3p2SH0vein2UfubngFCEdu9TLy54UxAjiJEvpsKHar2YTW6D5jMtiGWPFZCcJ++ccZnKCBv88ukK1nTmXCV0wT8XS86Ie7MoY9TYTJq7Vaw8PSP+yLjNweJvuBKx5ZEOw5MV+0kwsA5z1PYiisIDJv6mXbui5A7cmcqYwiN284eTShz5uVd/GqxGp87+rakxK7DOPR9ZA==
    USERNAME: AgAs1TGI8y+m9bC2vTx1DMGYHELfrZl7wygLi4DKNsHa4zt/uCOEf2niZZrM+PvfDYvGhvj6gyJv+AznQBz6Z4JVcWe1XEYH81whJRQKBIGI+Di88kRyl01pDWrbE7TAyjA54av/PhkG5TKp+motORXamicYPjUl2tmTc6jXBkqswnMVIvMuc5p1Y2xCAhswKQmGxYMeSdei3SCssF6VdB/2bc01nUsbntFx8Bm6gIBrB/w4ot03E2gQRWhkjHCQwyctHY/4kWt/rKEDXxJMMaZrZR9NqzXc2IfWbFlo08/ZOFudIn8FBfI2g66CEYzKV4K9DCYVib3EM7EBC4ZTILVbig7nxrQwHy2qusJS+Rslowdzlr05M1EFKCeQ5G+ps42IAD5p+D+NgU4z+v5Ubt6pfc/O6iBdOdk9dGixQUFq9awNgLC3Cxj37G3OWzrp1FjBGOvZ5jJJduqwD7xOJThiFSFlLdCfpgtFbe1JlkM2Blay2A5yz5hIQjcvwqDzUuVksajDRNtWSUVdwCKvYTSTGbnB52ilJWyZqgecnGkk1bhmEHpKILtTnSvNRGZXWCc08ofkSoSr47TLUhMk8k+GTxmRD1tzMtch4+1rCBFV5aONiYlErwe8ync9XMH/A9Tso2z5wYmoz9bW1wf0tpQgHyp/yyXYih82qXxIcCxew6GylVX5SSMOuGSC1TzkwNgVXFgwWjm/TNy2gu8=
  template:
    metadata:
      name: samba
      namespace: default
