apiVersion: v1
kind: Service
metadata:
  name: samba
  annotations:
    metallb.io/address-pool: address-pool
    external-dns.alpha.kubernetes.io/hostname: samba.local
spec:
  selector:
    app.kubernetes.io/name: samba
  type: LoadBalancer
  ports:
    - name: smb-server
      port: 445
      targetPort: 445
      protocol: TCP
