apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyze-bridge
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wyze-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wyze-bridge
    spec:
      containers:
      - name: wyze-bridge
        image: mrlt8/wyze-bridge:latest
        env:
          - name: WYZE_EMAIL
            valueFrom:
              secretKeyRef:
                name: wyze-bridge
                key: email
          - name: WYZE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wyze-bridge
                key: password
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
            - name: rtmp
              containerPort: 1935
            - name: rtsp
              containerPort: 8554
            - name: hls
              containerPort: 8888
            - name: webrtc
              containerPort: 8889
            - name: ice
              containerPort: 8189
              protocol: UDP
            - name: web-ui
              containerPort: 5000
