apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - root.yaml

  - argocd.yaml
  - metallb.yaml
  - mosquitto.yaml
  - openebs-jiva.yaml
  - pihole.yaml
  - transmission.yaml
