apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - root.yaml

  - argocd.yaml
  - caddy.yaml
  # - esphome.yaml
  - external-dns.yaml
  - home-assistant.yaml
  - jellyfin.yaml
  - longhorn.yaml
  - metallb.yaml
  - mosquitto.yaml
  - pihole.yaml
  - samba.yaml
  - sealed-secrets.yaml
  # - sickgear.yaml
  - transmission.yaml
  # - wyze-bridge.yaml
