apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wyze-bridge
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: wyze-bridge
    repoURL: https://github.com/TMaYaD/homelab.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
