apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: caddy
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: caddy
    spec:
      containers:
      - name: caddy
        image: caddy:2.7.5
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/caddy
        - name: persistant-storage
          mountPath: /data
          subPath: data
        - name: persistant-storage
          mountPath: /config
          subPath: config
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
      volumes:
      - name: config
        configMap:
          name: caddy
      - name: persistant-storage
        persistentVolumeClaim:
          claimName: caddy
