apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: caddy
  files:
  - Caddyfile

resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml

generatorOptions:
 disableNameSuffixHash: true
