apiVersion: v1
kind: Service
metadata:
  name: caddy
  annotations:
    # metallb.io/allow-shared-ip: "home-assistant-shared-ip"
    metallb.io/loadBalancerIPs: 10.10.10.100
    external-dns.alpha.kubernetes.io/hostname: caddy.local
spec:
  selector:
    app.kubernetes.io/name: caddy
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
