apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/role: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/role: mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/role: mqtt
    spec:
      containers:
        - name: broker
          image: eclipse-mosquitto:2.0.18
          # resources:
          #   limits:
          #     memory: "0.6Gi"
          #     cpu: "300m"
          #   requests:
          #     memory: "0.2Gi"
          #     cpu: "150m"
          ports:
            - name: mqtt
              containerPort: 1883
            - name: http
              containerPort: 9001
          volumeMounts:
            - name: config
              mountPath: "/mosquitto/config"
              readOnly: true
            # - name: conf.d
            #   mountPath: "/mosquitto/config/conf.d"
            #   readOnly: true
      volumes:
        - name: config
          configMap:
            name: mosquitto
        # - name: conf.d
        #   configMap:
        #     name: mosquitto-conf.d
