apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - secret.sealed.yaml
  - service.yaml

configMapGenerator:
- name: mosquitto
  files:
  - mosquitto.conf

generatorOptions:
 disableNameSuffixHash: true
