apiVersion: v1
kind: Service
metadata:
  name: mqtt
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.8.33
spec:
  selector:
    app.kubernetes.io/role: mqtt
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: mqtt
      # nodePort: 31883
    # - port: 9001
    #   targetPort: http
    #   nodePort: 39001
