apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole
  labels:
    app.kubernetes.io/name: pihole
data:
  TZ: "Asia/Kolkata"
  FTLCONF_dns_upstreams: "127.0.0.1#5053"
  FTLCONF_dns_revServers: 'true,10.10.8.0/22,10.10.8.1,local'
  FTLCONF_dns_listeningMode: "all"
