apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app.kubernetes.io/name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 80
              name: admin
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pihole
            - secretRef:
                name: pihole
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          # volumeMounts:
          #   - name: pihole
          #     mountPath: /etc/pihole
          #     subPath: etc
          #   - name: pihole
          #     mountPath: /etc/dnsmasq.d
          #     subPath: dnsmasq
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          ports:
            - containerPort: 5053
              name: dns
              protocol: UDP
            - containerPort: 5053
              name: dns-tcp
              protocol: TCP
          args:
            - proxy-dns
            - --port=5053
            - --upstream=https://1.1.1.1/dns-query
            - --upstream=https://1.0.0.1/dns-query
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "100m"
      # volumes:
      #   - name: pihole
      #     persistentVolumeClaim:
      #       claimName: pihole
