apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app.kubernetes.io/name: pihole

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 80
              name: admin
              protocol: TCP
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: DNSMASQ_LISTENING
              value: "all"
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "100m"
      #     volumeMounts:
      #       - name: pihole
      #         mountPath: /etc/pihole
      #         subPath: etc
      #       - name: pihole
      #         mountPath: /etc/dnsmasq.d
      #         subPath: dnsmasq
      # volumes:
      #   - name: pihole
      #     persistentVolumeClaim:
      #       claimName: pihole
