---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: default
spec:
  encryptedData:
    FTLCONF_webserver_api_password: AgB9Ml2jctvU98d/En6zwr9pJPWDpjAK/Ol8W9QSlRRPAibr9e2eC5o1JlO2QHvIREdT/IlJmbj7thD9ogywYIRmt2UY5Kr5snnafIbiJXIQMPPX6PC9wFAiF9NNhIsOS+CXT+ck3z6diBTPv+bZP3NaltKM5Gk0kBu/m5kZS0sOREzgY4lzVp6y7XpTEECmauenaGZWDdZS/bth4hkOv6oIQYTu1i+zCINqrTLG9JkcN4Uzk+cfkJliK99kS7uMDaAx6DSuzRg5CXMs2O4T2tUGZPo4QUDEjTxDdiOp7aCnb/B/USUSi8pSMumEi6qr/xlS2kkxm/fFEQXXzw3m8HNpkm6GkBzyji5YbfGdnEusQ9irjZPQSXuxRpLq9TUU7BjzepjUi+Tipjaa7S9yUwBYJL0cCJMc2axziSu9a0qkxOPvfflW3lZGM5IAe7njZaK6QoPvfs99nEnVC7j2XhBWJBKEpWTHeNzPAP7MzxmRV/2y7+B/BTKPifJtevn7/eMrBToLQKzZN6MXRtbr9IFTZm70+zNvhcJkQho9gtIfJo5tgdoU2DDyYOeAjCuk6usn7rOtwg/qEVq+7kSIit6fKTRRmmWzC/JAOWXzMR0VsVW1BkqK2kUMjBawvYBbRj9GBQevgZZ+OF2OYVcz/wyRTTcxFbsDrz/e2Iic6iuCmo6OSZLCeBT7iarPf5ufIa07V9Cxiis=
  template:
    metadata:
      name: pihole
      namespace: default
    type: Opaque
