apiVersion: v1
kind: Service
metadata:
  name: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.8.53
spec:
  selector:
    app.kubernetes.io/name: pihole
  type: LoadBalancer
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: admin
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-backup
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.8.35
spec:
  selector:
    app.kubernetes.io/name: pihole
  type: LoadBalancer
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: admin
      port: 80
      protocol: TCP
      targetPort: 80
