kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pihole
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Mi
