homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Kolkata

  # auth_providers:
  #   - type: trusted_networks
  #     trusted_networks:
  #       - 10.10.8.0/24
  #       - fd00::/8
  #     allow_bypass_login: true

default_config:

http:
  # ip_ban_enabled: false
  # login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

alexa:
  smart_home:
