homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Kolkata

  # auth_providers:
  #   - type: trusted_networks
  #     trusted_networks:
  #       - 10.10.8.0/21
  #       - fd00::/8
  #     allow_bypass_login: true

  packages: !include_dir_named packages

default_config:

lovelace:
  mode: yaml
  resources:
    - url: "/hacsfiles/mushroom-strategy/mushroom-strategy.js"
      type: module
    - url: "/hacsfiles/lovelace-mushroom/mushroom.js"
      type: module
    - url: "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js"
      type: module

wake_on_lan:

http:
  # ip_ban_enabled: false
  # login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

api:

alexa:
  smart_home:
    endpoint: https://api.eu.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret

# My own handmade automations
automation manual: !include_dir_merge_list automations/

# Automations I create in the UI
automation ui: !include automations.yaml

sensor:
  # Minimal configuration of the standard time and date sensor
  - platform: time_date
    display_options:
    - 'date_time_iso'
    - 'date'

# {"Vendor":"VOLTAS","Model":1,"Mode":"Cool","Power":"Off","Celsius":"On","Temp":27,"FanSpeed":"Auto","SwingV":"Auto","SwingH":"Auto","Quiet":"Off","Turbo":"Off","Econo":"On","Light":"Off","Filter":"Off","Clean":"Off","Beep":"Off","Sleep":0, "StateMode":"StoreOnly"}
mqtt:
  - climate:
      name: "Master AC"
      unique_id: id.master_ac
      device:
        identifiers: id.master_ac
        suggested_area: master
      modes:
      - "off"
      - cool
      - dry
      - fan_only
      swing_modes:
      - "auto"
      - "1"
      - "2"
      - "3"
      - "4"
      min_temp: 16
      max_temp: 30
      temp_step: 1
      initial: 25

      temperature_command_topic: "master/ir/cmnd/IRHVAC"
      temperature_command_template: '{"Temp": {{ value|int }}, "Incremental": true}'

      mode_command_topic: "master/ir/cmnd/IRHVAC"
      mode_command_template: '{"Power": "{{value if value=="off" else "on"}}", "Mode": "{{ value }}", "Incremental": true}'

      fan_mode_command_topic: "master/ir/cmnd/IRHVAC"
      fan_mode_command_template: '{"FanSpeed": "{{ value }}", "Incremental": true}'

  - climate:
      name: "Office AC"
      unique_id: id.office_ac
      device:
        identifiers: id.office_ac
        suggested_area: office
      modes:
      - "off"
      - cool
      - dry
      - fan_only
      swing_modes:
      - "auto"
      - "1"
      - "2"
      - "3"
      - "4"
      min_temp: 16
      max_temp: 30
      temp_step: 1
      initial: 25

      temperature_command_topic: "office/ir/cmnd/IRHVAC"
      temperature_command_template: '{"Temp": {{ value|int }}, "Incremental": true}'

      mode_command_topic: "office/ir/cmnd/IRHVAC"
      mode_command_template: '{"Power": "{{value if value=="off" else "on"}}", "Mode": "{{ value }}", "Incremental": true}'

      fan_mode_command_topic: "office/ir/cmnd/IRHVAC"
      fan_mode_command_template: '{"FanSpeed": "{{ value }}", "Incremental": true}'
