apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: home-assistant
  files:
  - configuration.yaml
  - ui-lovelace.yaml

# secretGenerator:
# - name: home-assistant
#   files:
#   - secrets.yaml

resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml

generatorOptions:
 disableNameSuffixHash: true
