---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  encryptedData:
    secrets.yaml: AgBL1vu+5BgjW1qYdwXkxM4+o/kvDErB1uDLg6PI6HoXI8zirqixfJAN312yITPEdgnib7fY+56jdKNuqp19enoVs83Yf1Tzt6ZXZUNJd/p74dRguES3xDaVWQnBjeMuRqQbcXiiYZJDlE+M9YAOyERWPCFr4wnl5/BUAHpc394BLV4BOymsbgrNimomqqrUInEIEZrl0EjR9gCALohOjPKgrse5TnfXgUEsme51f2U8zJWgdGllKBQ/si5vz5n5V96lFRmkGZWNngbnaFNg/VldAxD6955o1JuqPo7Ht6eySTFZj9EalOEqkjdnE4iSiuZ4pzP+EHgbHsnQrVFNeQ3J0ObOW0cuRxkJhiZ4wSjlwlsNYpnrXEy+5/aUZDbZb04rYYxvFldwuj8nqEMossGtTAmkcn84cSBQFzjbs7W9Ua3FJyhozHDwFkJSI1v9Suy1eVVT3pk3TAuLqj7C1MYng47OUh/idaiIv4VW6xF315jNDqS0UZ1b2KwmI7OQrVSztlmzlX+eCksaupplzSp9Uh6lT8/qkH1KbVotgwHnnQVEqirshTBBqRfTcPXrTfQoeeVeWLg/jwjB9uccf6jvWLLmjJJN9lLM9C2zqVlOh+kyWGMBHquKf8+5Y+GvXkNpp7nEI8+4eoGuFkBZycUcV1wLwybXHLBKM1Ke9JynUFw8i7N63tT9thHg+D5lgUgabAjN5xKLbeoJBJjZCm3GALdOXMQf4hfJHpiGWFUlVA9qJYM7Kwhjn5DVnPkK7YMGSWzPmPQECy6QOXX+0DvsPEnYeb4FvzwRK/e1yLD/kJwZqAH/Ojn4dkonjaMjGb7NeH/m+GYz8fLNG4ZFjogyxSIvovqZiH4SXfNfZe2011JQl5zLnXBZ82VbYTxXZfyo/KKxTWbsbq5y9KpXYbcjq4u3AD0QvgGPZnKIVYZt5DqWjukkH7Bmsu6rNzp6zhTvquuvhHYibQ9TG91zq9LXRO5nt5CHGz0/4o7a9zdgvZd3vp3WHS137iGyEk4a
  template:
    metadata:
      name: home-assistant
      namespace: default
