apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    # metallb.universe.tf/allow-shared-ip: "home-assistant-shared-ip"
    metallb.universe.tf/loadBalancerIPs: 10.10.8.36
    external-dns.alpha.kubernetes.io/hostname: ha.local
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8123
