apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.8.39
    external-dns.alpha.kubernetes.io/hostname: argocd.local
spec:
  type: LoadBalancer
