apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  annotations:
    metallb.io/address-pool: address-pool
    external-dns.alpha.kubernetes.io/hostname: argocd.local
spec:
  type: LoadBalancer
