apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:10.9.11
          ports:
            - containerPort: 8096
              name: http
          env:
            - name: JELLYFIN_PublishedServerUrl
              value: "http://jellyfin.local"
          volumeMounts:
            - mountPath: "/config"
              name: config-storage
            - mountPath: "/cache"
              name: cache-storage
            - mountPath: "/media"
              name: media-storage
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 1000m
              memory: 2048Mi
          # Enable GPU acceleration if available (optional)
          # securityContext:
          #   privileged: true
          # volumeMounts:
          # - mountPath: /dev/dri
          #   name: device-dri
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: cache-storage
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - name: media-storage
          persistentVolumeClaim:
            claimName: jellyfin-media
        # Uncomment for GPU acceleration
        # - name: device-dri
        #   hostPath:
        #     path: /dev/dri