apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: jellyfin
    repo: https://charts.truecharts.org
    version: 23.0.10
    includeCRDs: true
    namespace: jellyfin
    releaseName: jellyfin
    valuesInline:
      # Service Configuration
      service:
        main:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/address-pool: address-pool
            external-dns.alpha.kubernetes.io/hostname: jellyfin.local
          ports:
            http:
              port: 8096

      # Storage Configuration  
      persistence:
        config:
          enabled: true
          size: 10Gi
          storageClass: longhorn
          accessMode: ReadWriteOnce
        cache:
          enabled: true
          size: 20Gi
          storageClass: longhorn
          accessMode: ReadWriteOnce
        media:
          enabled: true
          size: 500Gi
          storageClass: longhorn
          accessMode: ReadWriteMany

      # Resource Configuration
      resources:
        limits:
          cpu: 2000m
          memory: 4096Mi
        requests:
          cpu: 1000m
          memory: 2048Mi

      # Image Configuration
      image:
        repository: jellyfin/jellyfin
        tag: 10.9.11

resources:
  - namespace.yaml