apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml

images:
  - name: lscr.io/linuxserver/jellyfin
    newTag: 2021.12.16
