apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    metallb.io/address-pool: address-pool
    external-dns.alpha.kubernetes.io/hostname: jellyfin.local
spec:
  selector:
    app.kubernetes.io/name: jellyfin
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      targetPort: 8096
      protocol: TCP
