apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  annotations:
    metallb.universe.tf/address-pool: address-pool
    external-dns.alpha.kubernetes.io/hostname: jellyfin.local
spec:
  selector:
    app.kubernetes.io/name: jellyfin
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8096
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8096
    - name: jellyfin
      protocol: TCP
      port: 8096
      targetPort: 8096