apiVersion: apps/v1
kind: Deployment
metadata:
  name: sickgear
  labels:
    app.kubernetes.io/name: sickgear
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sickgear
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sickgear
    spec:
      containers:
      - name: sickgear
        image: lscr.io/linuxserver/sickgear:3.30.5
        env:
        - name: TZ
          value: Asia/Kolkata
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP
        volumeMounts:
          - name: sickgear
            mountPath: /config
            subPath: config
          - name: sickgear
            mountPath: /tv
            subPath: tv
          - name: sickgear
            mountPath: /downloads
            subPath: downloads
      volumes:
        - name: sickgear
          persistentVolumeClaim:
            claimName: sickgear
