apiVersion: v1
kind: Service
metadata:
  name: sickgear
  annotations:
    metallb.io/address-pool: address-pool
    external-dns.alpha.kubernetes.io/hostname: sickgear.local
spec:
  selector:
    app.kubernetes.io/name: sickgear
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
