kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sickgear
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
