latitude: ENC[AES256_GCM,data:pGs6aKj3YiASpfBRVQ7XEdJs,iv:b/XbMYNsbSmBRrvGBPxHg2OqC6T2I2e9ZzUUtwLr4JI=,tag:LqycswKWqNRNd1H5mNH/Qw==,type:float]
longitude: ENC[AES256_GCM,data:+KY+pp13gY0+/EvWvxcx7EU=,iv:cAwIiI8wZWM7DXHrrfNRkU4lmG1Mw7LL+tcs9FohqDM=,tag:DoALaHghXgPUWq2NbWg/Ag==,type:float]
elevation: ENC[AES256_GCM,data:iQ==,iv:zypD883N/ukWsbBW9jbu8WoJsW2vNXBZjgIJyzbkxYU=,tag:vwYpLg1M4vXXxX9+qupKnw==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTFdOdFhvbUE3OGIvNm9I
            c21yaytMRzV1cFBtTnlUUXNtVXpTZjV6WlVvCnM3U0NNak1jdWYzREZ0czV4M1Qy
            anBYM1VxcDBtMGtjQi9EVElaL2EreTQKLS0tICttN0tEYmFDQm9PaW04NEp3YzMr
            eGRMNm4vdWNHM01EalFESVVWOHJoQjAK4ibZ7VOzXk6rMq3+FPvRUNwRmb51s2de
            nebFgPO9GQdAaz7B81YqXGkzkRHUztAmL2NNuvnHec2iEPBWawfyYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lt8uhkqym0x4ld3ufuj79pglflx2kw2gmnd25c804z6k3mtjl36q08n9x2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TjFLcmhwQStmaytQTVFh
            ZWJLcFU2emRtRUpQZW0rM281WmhtUlVNOXpFCmFNa3pHN3hkWmEzRFlGMm1mTSs3
            K3RaUmx0akllQngxa3FtdTlPQ0d6cGMKLS0tIGxOb1cySmZtMVhyTWFFb21pU3hC
            QVc3Wnl1cUs1VXlaSlE2cDAwTU8vcDQKUIOafhCDX/Pwir8erVfnQS/LTgcKHaOx
            UTvBzjqHMdapEHxa4JDVWFT4UZuG6i45RVrWbHENTytb1SyBOTBurQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lvmwy28trpw7msxk7krkkw4fvlw29layesvwtpk2ddssph0japdswcz3rz
    lastmodified: "2026-07-06T09:17:18Z"
    mac: ENC[AES256_GCM,data:ji4bDkV45UhcAJGmfznOd4hIrCEis1OB+0JefnZSxHKrGmYG6F2N0HzWL3DLEKhuX6X3ifKxp4gbHnmhdp80xM/crJxgWXNCh96SAcMkyxN8S00pvGHZKmZQhClALPCj6u7McVpdDU6+g/p2VyrZjd+j4UxIFOYSOING8TXvvXk=,iv:o1aiDcoxAU4LqOQJUynBFR/0mJqW8flaNKagMLBW2Hc=,tag:bGCDNt8Bbsirg8DNxzImYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
