apiVersion: v1
kind: Service
metadata:
  name: syncthing
  annotations:
    metallb.universe.tf/address-pool: address-pool
    external-dns.alpha.kubernetes.io/hostname: syncthing.local
spec:
  selector:
    app.kubernetes.io/name: syncthing
  type: LoadBalancer
  ports:
    - name: web
      port: 8384
      protocol: TCP
    - name: tcp-transfer
      port: 22000
      protocol: TCP
    - name: udp-transfer
      port: 22000
      protocol: UDP
    - name: local-discovery
      port: 21027
      protocol: UDP

