apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:latest
          ports:
            - containerPort: 9091
              name: web
              protocol: TCP
            - containerPort: 51413
              name: torrent-tcp
              protocol: TCP
            - containerPort: 51413
              name: torrent-udp
              protocol: UDP
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: USER
              value: "transmission"
            - name: PASS
              value: "transmission"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            limits:
              memory: "64Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "100m"
          volumeMounts:
            - name: transmission
              mountPath: /config
              subPath: config
            - name: transmission
              mountPath: /downloads
              subPath: downloads
            - name: transmission
              mountPath: /watch
              subPath: watch
        - name: smb-server
          image: dperson/samba
          args:
            - "-u"
            - $(USERNAME);$(PASSWORD)
            - "-s"
            - share;/smbshare/;yes;no;no;all;none
            - "-p"
          env:
            - name: PERMISSIONS
              value: "0777"
            - name: USERNAME
              value: transmission
            - name: PASSWORD
              value: transmission
            - name: USERID
              value: "1000"
            - name: GROUPID
              value: "1000"
          ports:
            - containerPort: 445
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /smbshare
              name: transmission
      volumes:
        - name: transmission
          persistentVolumeClaim:
            claimName: transmission
