apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app.kubernetes.io/name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: transmission
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: transmission
    spec:
      containers:
        - name: transmission
          image: lscr.io/linuxserver/transmission:4.0.6
          ports:
            - containerPort: 9091
              name: web
              protocol: TCP
            - containerPort: 51413
              name: torrent-tcp
              protocol: TCP
            - containerPort: 51413
              name: torrent-udp
              protocol: UDP
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: USER
              value: "transmission"
            - name: PASS
              value: "transmission"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: transmission
              mountPath: /config
              subPath: config
            - name: transmission
              mountPath: /watch
              subPath: watch
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: transmission
          persistentVolumeClaim:
            claimName: transmission
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
