---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transmission
  namespace: default
spec:
  encryptedData:
    password: AgAAq5cDSAwHer61XF6hPydRnakCDCAFpHjhTiaLazxg7o/eJXjT7xDfifJtwSzZZFlu42A1QPuZlN6tQ4QHeAvYdf2wYnzULn+lNrrnV8Lgxv4uKYsv6GWj6dBuHKIr+FyB25oLkqDj2ot2qNrntx8KTNTZDk6n/Ev3iWORQSPONH0l7PBa8oI0rpZmgF67q9SdTa3NjbK8d+Tr8RfKb82vF9d6vbDMucfUgCs1Su5qp0lBHP3mFSZa4KMBpuWrjvUjzbnDMWxswWGiiUhu7EJf44eRZ15/aRHtYCsFbJMUIXP9Om6d65Aq5+67vjLFuHdn0hZPQ+a2E5WVK88vJDTp/KwmFeRl10uEd1IBj+JmMqEXs8dtEREfUOAFKcXLcVUBL06Ru3Cr7nl7b29pucueWa14HhkcDp2F7HdhSefmnCJ5WOK4qw9vLnIHaAzv59qtbCZ1qkJHmedRsPKHecXBVSq9pxcJL8JBwWxQFHcU5g9oZc+uK5sXzhHf8BIlIrfXEqazCe5PhN9gMrHb1R5UbwG1itZoGfaQ59sa8cKJjErEEkuEa5oo5y5ml9vcWZ8W6SpSybm5E//IslQXyKqN/YaUoiJrBlZmkmm4OsD2IrBNf/KGu86o4IjtQ1nJt1N58OIMcjLfiY2LykPlI6/xqlDjEAMm0EzM9a0hV/kRlgnU5NyIdhhMm74UmksGXCybzB5erDX7aiEjtw==
  template:
    metadata:
      name: transmission
      namespace: default
