kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: transmission
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
