apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  labels:
    app.kubernetes.io/name: esphome
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: esphome
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: esphome
    spec:
      containers:
        - name: core
          image: ghcr.io/esphome/esphome:2023.9.1
          ports:
            - containerPort: 6052
          env:
            - name: ESPHOME_DASHBOARD_USE_PING
              value: "true"
            # - name: ESPHOME_DASHBOARD_USE_API
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_MDNS
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_SNAPSHOT
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_TEMPLATE
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_LOGS
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_DIAGNOSTICS
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_MANUAL
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_VERSION
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_RESTART
            #   value: "true"
            # - name: ESPHOME_DASHBOARD_USE_U
          volumeMounts:
            - mountPath: "/config"
              name: config
            - mountPath: "/config/common"
              name: config-common
            - mountPath: "/config/.esphome"
              name: persistent-storage
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
      volumes:
        - name: config
          configMap:
            name: esphome
        - name: config-common
          projected:
            sources:
              - configMap:
                  name: esphome-common
              - secret:
                  name: esphome
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: esphome
