apiVersion: v1
kind: Service
metadata:
  name: esphome
  annotations:
    # metallb.universe.tf/allow-shared-ip: "esphome-shared-ip"
    metallb.universe.tf/loadBalancerIPs: 10.10.8.37
    external-dns.alpha.kubernetes.io/hostname: esphome.local
spec:
  selector:
    app.kubernetes.io/name: esphome
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 6052
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: 8123
