kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: esphome
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
