apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/external-dns.git//kustomize?ref=v0.18.0

patches:
- path: deployment.patch.yaml
- path: adguard-webhook.yaml

secretGenerator:
- name: adguard-configuration
  files:
  - adguard-configuration.yaml

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.18.0
